server:
  port: 8081
spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/fornecedor
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    username: root
  application:
      name: fornecedor
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka